security:
    encoders:
        App\Entity\Professeurs:
            algorithm: 'auto'
        App\Entity\Etudiants:
            algorithm: 'auto'
        App\Entity\Secretaire:
            algorithm: 'auto'
        App\Entity\Admin:
            algorithm: 'auto'
        Symfony\Component\Security\Core\User\User:
            algorithm: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
                chain:
                    providers: [in_database_admin_login, in_database_etudiant_login,in_database_etudiant_mail,in_database_secretaire_login,in_database_secretaire_mail, in_database_professeur_login, in_database_professeur_mail]
        in_database_admin_login:
            entity:
                class: App\Entity\Admin
                property: login
        in_database_etudiant_mail:
            entity:
                class: App\Entity\Etudiants
                property: mailAcademique

        in_database_etudiant_login:
            entity:
                class: App\Entity\Etudiants
                property: login

        in_database_professeur_mail:
            entity:
                class: App\Entity\Professeurs
                property: mailAcademique

        in_database_professeur_login:
            entity:
                class: App\Entity\Professeurs
                property: login

        in_database_secretaire_mail:
            entity:
                class: App\Entity\Secretaire
                property: mailAcademique

        in_database_secretaire_login:
            entity:
                class: App\Entity\Secretaire
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: chain_provider
            form_login:
                login_path: connexion
                check_path: connexion

            logout:
                path: deconnexion
                target: /

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_ETUDIANT: ROLE_USER
        ROLE_PROFESSEUR: ROLE_USER
        ROLE_SECRETAIRE: ROLE_USER
        ROLE_PROFESSEURRESPONSABLE: [ROLE_PROFESSEUR, ROLE_USER]
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/informations/globales, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^informations/classes, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/etudiant_account, role: ROLE_ETUDIANT }
        - { path: ^/professeur_account, role: ROLE_PROFESSEUR }
        - { path: ^/secretaire_account, role: ROLE_SECRETAIRE }
        - { path: ^/etudiant, role: [ROLE_PROFESSEURRESPONSABLE, ROLE_ADMIN] }
        - { path: ^/secretaire, role: [ROLE_ADMIN] }
        - { path: ^/professeur, role: [ROLE_ADMIN] }
        - { path: ^/classe, role: [ROLE_ADMIN] }
        - { path: ^/article, role: [ROLE_SECRETAIRE, ROLE_PROFESSEURRESPONSABLE] }
